[[redirects]]
from = "https://krishankantray.netlify.app"
to = "https://krishankantray.com"
status = 301
force = false
query = {path = ":path"}
conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
